export const brandMarketChoice = [
	"Houston, TX",
	"Atlanta, GA",
	"Many Markets",
	"Pheonix, AR",
	"Denver, CO",
	"Nashville, TN",
	"Pittsburgh, PA",
	"Austin, TX",
	"Baltimore, MD",
	"Bay Area, CA",
	"Miami, FL",
	"Scottsdale, AR",
	"Tuscon, AR",
	"Tampa, FL",
	"New York City, NY",
	"Grand Rapids, MI",
	"Asheville, NC",
	"Charlotte, NC",
	"Fort Worth, TX",
	"Lexington, KY",
	"Dallas, TX",
	"San Diego, CA",
	"Las Vegas, NV",
	"San Jose, CA",
	"Los Angeles, CA",
	"Washington DC",
	"Seattle, WA",
	"San Antonio, TX",
	"Boston, MA",
	"Irvine, CA",
	"International",
] as const;
